/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./src/components/Appbar.vue')['default']
    Blanck: typeof import('./src/components/Blanck.vue')['default']
    Blank: typeof import('./src/components/Blank.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    copy: typeof import('./src/components/Home copy.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
